import { createContext, useContext, useState, ReactNode } from 'react';

type Lang = 'nl' | 'en';

const translations = {
  nl: {
    // Auth
    'auth.title': 'Lactaat Test',
    'auth.loginDesc': 'Log in om verder te gaan',
    'auth.registerDesc': 'Maak een account aan',
    'auth.email': 'Email',
    'auth.password': 'Wachtwoord',
    'auth.fullName': 'Volledige naam',
    'auth.login': 'Inloggen',
    'auth.register': 'Registreren',
    'auth.submitting': 'Bezig...',
    'auth.forgotPassword': 'Wachtwoord vergeten?',
    'auth.noAccount': 'Nog geen account?',
    'auth.hasAccount': 'Al een account?',
    'auth.registerLink': 'Registreer',
    'auth.loginLink': 'Log in',
    'auth.accountCreated': 'Account aangemaakt',
    'auth.checkEmail': 'Controleer je email om je account te bevestigen.',
    'auth.error': 'Fout',
    'auth.fillEmail': 'Vul je emailadres in',
    'auth.emailSent': 'Email verstuurd',
    'auth.checkInbox': 'Controleer je inbox voor de reset link.',
    'auth.demoLogin': 'Demo: Inloggen als Tom',
    'auth.publicDemo': 'Bekijk publieke demo',
    // Landing
    'landing.badge': 'Lactaat Analyse Platform',
    'landing.headline1': 'Professionele lactaat',
    'landing.headline2': 'drempelanalyse',
    'landing.sub': 'Wetenschappelijk onderbouwde tools voor coaches en sporters. Bepaal LT1 en LT2 nauwkeurig en optimaliseer trainingsintensiteit.',
    'landing.cta': 'Aan de slag',
    'landing.login': 'Inloggen',
    'landing.f1title': 'Meerdere methoden',
    'landing.f1desc': 'Dmax, Modified Dmax, LTP en vaste drempel — alle erkende methoden in één platform.',
    'landing.f2title': 'Directe visualisatie',
    'landing.f2desc': 'Lactaatcurve, drempelpunten en trainingszones live in beeld zodra data is ingevoerd.',
    'landing.f3title': 'Atleetbeheer',
    'landing.f3desc': 'Sla testresultaten op per atleet en volg progressie over meerdere testsessies.',
    'landing.f4title': 'Exporteerbaar',
    'landing.f4desc': 'Resultaten en zones overzichtelijk gepresenteerd, klaar voor rapportage aan sporter of staf.',
    'landing.footer': '© 2026 Lactaat Test. Alle rechten voorbehouden.',
    // Common
    'common.error': 'Fout',
    'common.save': 'Opslaan',
    'common.saving': 'Opslaan...',
    'common.loading': 'Laden...',
    'common.back': 'Terug',
    'common.cancel': 'Annuleren',
    'common.confirm': 'Bevestigen',
    'common.delete': 'Verwijderen',
    'common.edit': 'Bewerken',
    'common.or': 'OF',
    'common.next': 'Volgende',
    'common.unexpectedError': 'Er is een onverwachte fout opgetreden.',
    // AppNav
    'nav.demoNotice': 'Je bekijkt een demo account.',
    'nav.startFree': 'Start gratis →',
    'nav.signOut': 'Uitloggen',
    'nav.betaUnlimited': 'Onbeperkte analyses',
    'nav.noTokens': 'Geen analyses meer',
    'nav.tokensAvailable': 'analyse(s) beschikbaar',
    // StepNav
    'step.getSet': 'PROTOCOL',
    'step.test': 'DATA',
    'step.analyze': 'ANALYSE',
    // Dashboard
    'dash.status': 'Status: Arctic High',
    'dash.athletes': 'Atleten',
    'dash.addAthlete': '+ Atleet toevoegen',
    'dash.activeTest': 'Actieve test',
    'dash.ready': 'Klaar',
    'dash.lastLactate': 'Laatste Lactaat',
    'dash.noTests': 'Geen tests',
    'dash.tests': 'tests',
    'dash.systemReady': 'Systeem Klaarmaken',
    'dash.noAthletes': 'Geen actieve atleten gevonden. Volg de protocol stappen voor een zuivere meting.',
    'dash.step1title': 'Voeg atleet toe',
    'dash.step1desc': 'Importeer profiel of maak een nieuwe coach-ID aan.',
    'dash.step2title': 'Koppel Sensoren',
    'dash.step2desc': 'Zorg dat de Bluetooth analyzer is ingeschakeld.',
    'dash.step3title': 'Start de Test',
    'dash.step3desc': 'De data-flow start automatisch na de eerste strip.',
    'dash.newAthlete': 'Nieuwe atleet',
    'dash.enterName': 'Voer de naam van de atleet in.',
    'dash.namePlaceholder': 'Naam *',
    'dash.adding': 'Bezig...',
    'dash.add': 'Toevoegen',
    'dash.athleteAdded': 'Atleet toegevoegd',
    'dash.athleteDeleted': 'Atleet verwijderd',
    'dash.clubName': 'Clubnaam',
    'dash.myClub': 'Mijn Club',
    // AthleteDetail
    'detail.athletes': 'Atleten',
    'detail.precision': 'T4mmol Precisie',
    'detail.testsLabel': 'Tests',
    'detail.sessions': 'sessies',
    'detail.avgTempo': 'Gem. Tempo',
    'detail.newTest': '+ Nieuwe Test',
    'detail.history': 'Geschiedenis',
    'detail.lastTests': 'Laatste {n} tests',
    'detail.noTests': 'Nog geen tests uitgevoerd.',
    'detail.lt2': 'Lactaatdrempel 2',
    'detail.lt1': 'Aerobe drempel',
    'detail.steps': 'stappen',
    'detail.deleteTest': 'Test verwijderen?',
    'detail.editAthlete': 'Atleet bewerken',
    'detail.editDesc': 'Wijzig de gegevens van de atleet.',
    'detail.sport': 'Sport',
    'detail.notes': 'Notities',
    'detail.athleteUpdated': 'Atleet bijgewerkt',
    'detail.testDeleted': 'Test verwijderd',
    // AthleteTest / TestPage
    'test.allAthletes': 'Alle atleten',
    'test.viewTest': 'Test bekijken',
    'test.newTest': 'Nieuwe test',
    'test.fieldTest': 'Veldtest',
    'test.labTest': 'Inspanningstest',
    'test.stepsGenerated': 'Stappen gegenereerd',
    'test.stepsReady': 'stappen klaargezet.',
    'test.calculationDone': 'Berekening voltooid',
    'test.testSaved': 'Test opgeslagen',
    // Protocol
    'protocol.setup': 'Protocol instellen',
    'protocol.info': 'Stel starttempo, increment en stapafstand in voordat je begint.',
    'protocol.startPace': 'Starttempo (min/km)',
    'protocol.firstStep': 'Eerste stap',
    'protocol.increment': 'Increment (mm:ss sneller)',
    'protocol.fasterPerStep': 'Sneller per stap',
    'protocol.stepDistance': 'Stapafstand (meter)',
    'protocol.typical': 'Typisch: 1200 / 1600 / 2000m',
    'protocol.allOut': 'Laatste all-out inspanning',
    'protocol.allOutDesc': 'Maximale inspanning voor VO₂max/MAS bepaling',
    'protocol.allOutDistance': 'Afstand (meter)',
    'protocol.preview': 'Protocol preview',
    'protocol.generate': 'Genereer stappen naar Data Invoer',
    'protocol.preparation': 'Voorbereiding',
    'protocol.testProcedure': 'Testverloop',
    'protocol.prep1title': '48u voor de test',
    'protocol.prep1desc': 'Geen zware training. Rust of lichte activiteit maximaal.',
    'protocol.prep2title': 'Voeding',
    'protocol.prep2desc': 'Geen voedsel 2u voor de test. Geen cafeïne 4u voor de test. Goed gehydrateerd. Normale koolhydraatinname de dag ervoor.',
    'protocol.prep3title': 'Materiaal',
    'protocol.prep3desc': 'Lactaatmeter (bv. Lactate Plus / Lactate Pro 2), teststrips, lancetten (28G), alcoholdoekjes, papieren handdoek, hartslagband, loopband (1% helling).',
    'protocol.restMeasure': 'Rustmeting',
    'protocol.restDesc': 'Meet rustlactaat vóór de warming-up. Normaal: 0.5–1.5 mmol/L. Bij > 2.5 mmol/L: check voeding/stress.',
    'protocol.warmup': 'Warming-up (15 min)',
    'protocol.bloodSample': 'Bloedafname',
    'protocol.bloodDesc': 'Reinig prikplaats met alcohol. Prik, veeg eerste druppel weg, test de tweede druppel. Noteer: lactaat (mmol/L), hartslag (einde stap).',
    'protocol.cooldown': 'Cooling down',
    'protocol.cooldownDesc': '10–15 min uitlopen op lage intensiteit. Eventueel nog een laatste lactaatmeting na 5 min cooldown.',
    // Data Input
    'data.stepData': 'Stapgegevens',
    'data.steps': 'stappen',
    'data.step': 'Stap',
    'data.time': 'Tijd',
    'data.lactate': 'Lactaat',
    'data.hr': 'HR',
    'data.minutes': 'Minuten',
    'data.seconds': 'Seconden',
    'data.addStep': 'Stap toevoegen',
    'data.calculate': '🧮 Berekenen',
    'data.imported': 'Geïmporteerd',
    'data.stepsLoaded': 'stappen geladen.',
    'data.invalidJson': 'Ongeldig JSON bestand.',
    'data.noStepsFound': 'Geen stappen gevonden in JSON bestand.',
    'data.noUsableSteps': 'Geen bruikbare stappen gevonden.',
    'data.onlyJson': 'Alleen JSON bestanden.',
    'data.restingLactate': 'Rustlactaat',
    'data.testDate': 'Testdatum',
    'data.athlete': 'Atleet',
    'data.name': 'Naam',
    // Results
    'results.enterData': 'Voer testgegevens in en klik op "Berekenen".',
    'results.noResults': 'Geen berekende resultaten beschikbaar.',
    'results.aerobicThreshold': 'Aerobe drempel',
    'results.anaerobicThreshold': 'Anaerobe drempel',
    'results.lactateCurve': 'Lactaatcurve',
    'results.shareWhatsApp': 'Deel via WhatsApp',
    'results.shareImage': 'Deel als afbeelding',
    'results.copied': 'GEKOPIEERD',
    'results.copy': 'KOPIEER',
    'results.creatingLink': 'Link aanmaken...',
    'results.shareResults': 'Deel resultaten met atleet',
    'results.calculateFirst': 'Eerst data invoeren en berekenen om resultaten te zien.',
    // Zones
    'zones.calculateFirst': 'Eerst berekenen om trainingszones te zien.',
    'zones.noResults': 'Geen resultaten beschikbaar. Ga naar Data en klik op Berekenen.',
    'zones.hrVsTempo': 'Hartslag vs Tempo',
    'zones.pace': 'Tempo (min/km)',
    // Zone names
    'zone.1': 'Zone 1',
    'zone.2': 'Zone 2',
    'zone.3': 'Zone 3',
    'zone.4': 'Zone 4',
    'zone.5': 'Zone 5',
    'zone.1label': 'Herstel',
    'zone.2label': 'Aeroob (Endurance)',
    'zone.3label': 'Tempo',
    'zone.4label': 'Drempel',
    'zone.5label': 'VO₂max',
    'zone.1desc': 'Zeer licht, actief herstel',
    'zone.2desc': 'Duurloop, vetverbranding, basis',
    'zone.3desc': 'Stevig tempo, marathon/HM-tempo',
    'zone.4desc': 'Rond anaerobe drempel, 10K-tempo',
    'zone.5desc': 'Intervallen, maximale inspanning',
    // WhatsApp
    'wa.title': '🏃 *Lactaattest Resultaten*',
    'wa.aerobic': 'Aerobe drempel (LT1)',
    'wa.anaerobic': 'Anaerobe drempel (LT2)',
    'wa.zones': '📊 *Trainingszones:*',
    'wa.via': '_Via MyLactest_',
  },
  en: {
    // Auth
    'auth.title': 'Lactate Test',
    'auth.loginDesc': 'Sign in to continue',
    'auth.registerDesc': 'Create an account',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.fullName': 'Full name',
    'auth.login': 'Sign in',
    'auth.register': 'Register',
    'auth.submitting': 'Loading...',
    'auth.forgotPassword': 'Forgot password?',
    'auth.noAccount': 'No account yet?',
    'auth.hasAccount': 'Already have an account?',
    'auth.registerLink': 'Register',
    'auth.loginLink': 'Sign in',
    'auth.accountCreated': 'Account created',
    'auth.checkEmail': 'Check your email to confirm your account.',
    'auth.error': 'Error',
    'auth.fillEmail': 'Enter your email address',
    'auth.emailSent': 'Email sent',
    'auth.checkInbox': 'Check your inbox for the reset link.',
    'auth.demoLogin': 'Demo: Sign in as Tom',
    'auth.publicDemo': 'View public demo',
    // Landing
    'landing.badge': 'Lactate Analysis Platform',
    'landing.headline1': 'Professional lactate',
    'landing.headline2': 'threshold analysis',
    'landing.sub': 'Science-backed tools for coaches and athletes. Accurately determine LT1 and LT2 and optimise training intensity.',
    'landing.cta': 'Get started',
    'landing.login': 'Sign in',
    'landing.f1title': 'Multiple methods',
    'landing.f1desc': 'Dmax, Modified Dmax, LTP and fixed threshold — all recognised methods in one platform.',
    'landing.f2title': 'Instant visualisation',
    'landing.f2desc': 'Lactate curve, threshold points and training zones rendered live as data is entered.',
    'landing.f3title': 'Athlete management',
    'landing.f3desc': 'Store test results per athlete and track progression across multiple test sessions.',
    'landing.f4title': 'Exportable',
    'landing.f4desc': 'Results and zones clearly presented, ready for reporting to the athlete or coaching staff.',
    'landing.footer': '© 2026 Lactate Test. All rights reserved.',
    // Common
    'common.error': 'Error',
    'common.save': 'Save',
    'common.saving': 'Saving...',
    'common.loading': 'Loading...',
    'common.back': 'Back',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.or': 'OR',
    'common.next': 'Next',
    'common.unexpectedError': 'An unexpected error occurred.',
    // AppNav
    'nav.demoNotice': 'You are viewing a demo account.',
    'nav.startFree': 'Start free →',
    'nav.signOut': 'Sign out',
    'nav.betaUnlimited': 'Beta — unlimited analyses',
    'nav.noTokens': 'No tokens left',
    'nav.tokensAvailable': 'analysis/analyses available',
    // StepNav
    'step.getSet': 'PROTOCOL',
    'step.test': 'DATA',
    'step.analyze': 'ANALYSIS',
    // Dashboard
    'dash.status': 'Status: Arctic High',
    'dash.athletes': 'Athletes',
    'dash.addAthlete': '+ Add Athlete',
    'dash.activeTest': 'Active test',
    'dash.ready': 'Ready',
    'dash.lastLactate': 'Last Lactate',
    'dash.noTests': 'No tests',
    'dash.tests': 'tests',
    'dash.systemReady': 'System Setup',
    'dash.noAthletes': 'No active athletes found. Follow the protocol steps for an accurate measurement.',
    'dash.step1title': 'Add athlete',
    'dash.step1desc': 'Import profile or create a new coach ID.',
    'dash.step2title': 'Connect Sensors',
    'dash.step2desc': 'Make sure the Bluetooth analyzer is turned on.',
    'dash.step3title': 'Start the Test',
    'dash.step3desc': 'Data flow starts automatically after the first strip.',
    'dash.newAthlete': 'New athlete',
    'dash.enterName': 'Enter the athlete\'s name.',
    'dash.namePlaceholder': 'Name *',
    'dash.adding': 'Adding...',
    'dash.add': 'Add',
    'dash.athleteAdded': 'Athlete added',
    'dash.athleteDeleted': 'Athlete deleted',
    'dash.clubName': 'Club name',
    'dash.myClub': 'My Club',
    // AthleteDetail
    'detail.athletes': 'Athletes',
    'detail.precision': 'T4mmol Precision',
    'detail.testsLabel': 'Tests',
    'detail.sessions': 'sessions',
    'detail.avgTempo': 'Avg Pace',
    'detail.newTest': '+ New Test',
    'detail.history': 'History',
    'detail.lastTests': 'Last {n} tests',
    'detail.noTests': 'No tests performed yet.',
    'detail.lt2': 'Lactate Threshold 2',
    'detail.lt1': 'Aerobic Threshold',
    'detail.steps': 'steps',
    'detail.deleteTest': 'Delete test?',
    'detail.editAthlete': 'Edit athlete',
    'detail.editDesc': 'Modify the athlete\'s details.',
    'detail.sport': 'Sport',
    'detail.notes': 'Notes',
    'detail.athleteUpdated': 'Athlete updated',
    'detail.testDeleted': 'Test deleted',
    // AthleteTest / TestPage
    'test.allAthletes': 'All athletes',
    'test.viewTest': 'View test',
    'test.newTest': 'New test',
    'test.fieldTest': 'Field test',
    'test.labTest': 'Exercise test',
    'test.stepsGenerated': 'Steps generated',
    'test.stepsReady': 'steps ready.',
    'test.calculationDone': 'Calculation complete',
    'test.testSaved': 'Test saved',
    // Protocol
    'protocol.setup': 'Protocol setup',
    'protocol.info': 'Set start pace, increment and step distance before you begin.',
    'protocol.startPace': 'Start pace (min/km)',
    'protocol.firstStep': 'First step',
    'protocol.increment': 'Increment (mm:ss faster)',
    'protocol.fasterPerStep': 'Faster per step',
    'protocol.stepDistance': 'Step distance (metres)',
    'protocol.typical': 'Typical: 1200 / 1600 / 2000m',
    'protocol.allOut': 'Final all-out effort',
    'protocol.allOutDesc': 'Maximum effort for VO₂max/MAS determination',
    'protocol.allOutDistance': 'Distance (metres)',
    'protocol.preview': 'Protocol preview',
    'protocol.generate': 'Generate steps to Data Entry',
    'protocol.preparation': 'Preparation',
    'protocol.testProcedure': 'Test procedure',
    'protocol.prep1title': '48h before the test',
    'protocol.prep1desc': 'No heavy training. Rest or light activity only.',
    'protocol.prep2title': 'Nutrition',
    'protocol.prep2desc': 'No food 2h before the test. No caffeine 4h before. Well hydrated. Normal carbohydrate intake the day before.',
    'protocol.prep3title': 'Equipment',
    'protocol.prep3desc': 'Lactate meter (e.g. Lactate Plus / Lactate Pro 2), test strips, lancets (28G), alcohol swabs, paper towel, heart rate strap, treadmill (1% incline).',
    'protocol.restMeasure': 'Resting measurement',
    'protocol.restDesc': 'Measure resting lactate before warm-up. Normal: 0.5–1.5 mmol/L. If > 2.5 mmol/L: check nutrition/stress.',
    'protocol.warmup': 'Warm-up (15 min)',
    'protocol.bloodSample': 'Blood sample',
    'protocol.bloodDesc': 'Clean puncture site with alcohol. Prick, wipe first drop, test the second drop. Record: lactate (mmol/L), heart rate (end of step).',
    'protocol.cooldown': 'Cool down',
    'protocol.cooldownDesc': '10–15 min easy jog at low intensity. Optionally take a final lactate measurement after 5 min cooldown.',
    // Data Input
    'data.stepData': 'Step data',
    'data.steps': 'steps',
    'data.step': 'Step',
    'data.time': 'Time',
    'data.lactate': 'Lactate',
    'data.hr': 'HR',
    'data.minutes': 'Minutes',
    'data.seconds': 'Seconds',
    'data.addStep': 'Add step',
    'data.calculate': '🧮 Calculate',
    'data.imported': 'Imported',
    'data.stepsLoaded': 'steps loaded.',
    'data.invalidJson': 'Invalid JSON file.',
    'data.noStepsFound': 'No steps found in JSON file.',
    'data.noUsableSteps': 'No usable steps found.',
    'data.onlyJson': 'JSON files only.',
    'data.restingLactate': 'Resting lactate',
    'data.testDate': 'Test date',
    'data.athlete': 'Athlete',
    'data.name': 'Name',
    // Results
    'results.enterData': 'Enter test data and click "Calculate".',
    'results.noResults': 'No calculated results available.',
    'results.aerobicThreshold': 'Aerobic threshold',
    'results.anaerobicThreshold': 'Anaerobic threshold',
    'results.lactateCurve': 'Lactate curve',
    'results.shareWhatsApp': 'Share via WhatsApp',
    'results.shareImage': 'Share as image',
    'results.copied': 'COPIED',
    'results.copy': 'COPY',
    'results.creatingLink': 'Creating link...',
    'results.shareResults': 'Share results with athlete',
    'results.calculateFirst': 'Enter data and calculate first to see results.',
    // Zones
    'zones.calculateFirst': 'Calculate first to see training zones.',
    'zones.noResults': 'No results available. Go to Data and click Calculate.',
    'zones.hrVsTempo': 'Heart Rate vs Pace',
    'zones.pace': 'Pace (min/km)',
    // Zone names
    'zone.1': 'Zone 1',
    'zone.2': 'Zone 2',
    'zone.3': 'Zone 3',
    'zone.4': 'Zone 4',
    'zone.5': 'Zone 5',
    'zone.1label': 'Recovery',
    'zone.2label': 'Aerobic (Endurance)',
    'zone.3label': 'Tempo',
    'zone.4label': 'Threshold',
    'zone.5label': 'VO₂max',
    'zone.1desc': 'Very light, active recovery',
    'zone.2desc': 'Easy runs, fat burning, base',
    'zone.3desc': 'Steady tempo, marathon/HM pace',
    'zone.4desc': 'Around anaerobic threshold, 10K pace',
    'zone.5desc': 'Intervals, maximum effort',
    // WhatsApp
    'wa.title': '🏃 *Lactate Test Results*',
    'wa.aerobic': 'Aerobic threshold (LT1)',
    'wa.anaerobic': 'Anaerobic threshold (LT2)',
    'wa.zones': '📊 *Training zones:*',
    'wa.via': '_Via MyLactest_',
  },
} as const;

type TranslationKey = keyof typeof translations.nl;

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Lang>(() => {
    return (localStorage.getItem('lang') as Lang) || 'nl';
  });

  const setLang = (l: Lang) => {
    localStorage.setItem('lang', l);
    setLangState(l);
  };

  const t = (key: TranslationKey): string => translations[lang][key];

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLang = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLang must be used within LanguageProvider');
  return ctx;
};
